# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'medium-sdk-swift-sample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medium-sdk-swift-sample
  pod 'MediumSDKSwift', '0.0.4'
end
